//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbAsanHesabEntities : DbContext
    {
        public dbAsanHesabEntities()
            : base("name=dbAsanHesabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBankAccount> tblBankAccount { get; set; }
        public virtual DbSet<tblFee> tblFee { get; set; }
        public virtual DbSet<tblFeeCategory> tblFeeCategory { get; set; }
        public virtual DbSet<tblFeeCategoryGroup> tblFeeCategoryGroup { get; set; }
        public virtual DbSet<tblIncome> tblIncome { get; set; }
        public virtual DbSet<tblIncomeCategory> tblIncomeCategory { get; set; }
        public virtual DbSet<tblIncomeCategoryGroup> tblIncomeCategoryGroup { get; set; }
        public virtual DbSet<tblLicense> tblLicense { get; set; }
        public virtual DbSet<tblPaymentType> tblPaymentType { get; set; }
        public virtual DbSet<tblPostType> tblPostType { get; set; }
        public virtual DbSet<tblSecurityAccess> tblSecurityAccess { get; set; }
        public virtual DbSet<tblSecurityQuestion> tblSecurityQuestion { get; set; }
        public virtual DbSet<tblSundry> tblSundry { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<viewFeeInfo> viewFeeInfo { get; set; }
        public virtual DbSet<viewIncomeInfo> viewIncomeInfo { get; set; }
    
        public virtual ObjectResult<spSelectFeeInfo_Result> spSelectFeeInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectFeeInfo_Result>("spSelectFeeInfo");
        }
    
        public virtual ObjectResult<spSelectIncomeInfo_Result> spSelectIncomeInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectIncomeInfo_Result>("spSelectIncomeInfo");
        }
    }
}
