//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewFeeInfo
    {
        public int Id { get; set; }
        public Nullable<int> FeeCategory_Id { get; set; }
        public Nullable<int> BankAccont_Id { get; set; }
        public string FeeDate { get; set; }
        public string FeeTime { get; set; }
        public Nullable<long> Amount { get; set; }
        public string ReceiptNumber { get; set; }
        public string FeeDescription { get; set; }
        public byte PaymentId { get; set; }
        public string BankName { get; set; }
        public string Category { get; set; }
    }
}
